// <auto-generated />
namespace ExemploEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class perfilnop170715 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perfilnop170715));
        
        string IMigrationMetadata.Id
        {
            get { return "201507171633228_perfil-nop-170715"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
